elementId = 0;
color = $00FFFFFF;
drawMe = true;
isActive = false;
isHot = false;
isDragging = false;
grabOffsetX = 0; // Use the grab values to maintain offset when dragging elements
grabOffsetY = 0;
boundsWidth = 128;
boundsHeight = 24;
boundsX1 = 0;
boundsY1 = 0;
boundsX2 = 0;
boundsY2 = 0;
activatedFunction = undefined;
deselect = undefined;